# Generated by Django 2.2.5 on 2020-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researchExp', models.IntegerField()),
                ('industryExp', models.IntegerField()),
                ('toeflScore', models.IntegerField()),
                ('internExp', models.IntegerField()),
                ('greV', models.IntegerField()),
                ('greQ', models.IntegerField()),
                ('greA', models.IntegerField()),
                ('cgpa_4', models.IntegerField()),
            ],
        ),
    ]
